### ISSUE TITLE
for noobs

### ISSUE THREAD

**Issue by jfbleach** [oracle/oracle-db-tools#11]
A short piece in the read me on how to run your example scripts would be great for those of us new to sqlcl.  Not knowing how to run scripts in sqlcl, I finally found an example in an old closed issue. 
Example:
script apx
apx workspace

I didn't realize "script apx" was just the load command and didn't enter the second line. I expected something to happen and was left wondering what happened.

**Comment by totierne** [comment]
SQL> help
For help on a topic type help <topic> 
List of Help topics available:
/                @                @@               ACCEPT           
APEX             APPEND           ARCHIVE_LOG      BREAK            
BTITLE           CD               CHANGE           CLEAR            
COMPUTE          CONNECT          COPY             CTAS             
DEFINE           DEL              DESCRIBE         DISCONNECT       
EXECUTE          EXIT             FIND             FORMAT           
HISTORY          HOST             INFORMATION      INPUT            
LOAD             NET              OERR             PASSWORD         
PRINT            PROMPT           QUIT             REMARK           
RESERVED_WORDS   REST             RUN              SAVE             
SET              SETERRORL        SHOW             SHUTDOWN         
SPOOL            SSHTUNNEL        START            STARTUP          
TIMING           TNSPING          TTITLE           UNDEFINE         
WHENEVER         WHICH            XQUERY  
(note script is missing from the list above which is a bug) SQL> help script
SQLcl scripting is based on Java's JSR-223 which allows scripting languages to be executed from the Java VM. There are a number of languages that can be plugged in with the NashHorn Javascript engine being included in Java. 

The addition of client side scripting will allow control flow in the sql scripts themselves. It also allow for things like file access, greater control on host commands, leverage various javascript libraries, and the ability to leverage java.

To run a script simply type: script <script name>  If there is no file extension passed along it assumes a .js.

Examples at https://github.com/oracle/oracle-db-tools/tree/master/sqlcl/examples

**Comment by gvenzl** [comment]
Hi @totierne, can you add a short paragraph on that in the ReadMe as @jfbleach suggested?

**Comment by krisrice** [comment]
Good point I should put the blog link into each script as well. For example the one you mentioned is outlined here: http://krisrice.io/2016-10-11-export-apex-application-with-sqlcl/

**Comment by bamcgill** [comment]
closing this as we have another Pull request   https://github.com/oracle/oracle-db-tools/pull/44
