### ISSUE TITLE
copy files from/to local direcetory into database directory

### ISSUE THREAD

**Issue by jdonnerstag** [oracle/oracle-db-tools#12]
Hi,

Unfortunately I don't have access to the server running the Oracle RDBMS. But I need to copy files from/to my local server/laptop into a Directory configured in Oracle for expdp/impdp purposes. I understand I somehow can use UTL_FILE.PUT_FILE() but don't know the details. I'd guess that SQLcl scripts could somehow be used. May be you can help me with the script? Additional, since impdp/expdp writes log file into the Oracle directory, I'd like to print them locally (== copy <from> <stdout> | less)

Thanks a lot for your help
/Juergen

**Comment by krisrice** [comment]
That is an interesting use. Essentially>
kick off a datapump job
Use UTL_FILE to read the remote files and write it local.

Reading the remote file would be a variation on this script:
   https://github.com/oracle/oracle-db-tools/blob/master/sqlcl/examples/blob2file.sql
