### ISSUE TITLE
Common 'header' for scripts

### ISSUE THREAD

**Issue by jdonnerstag** [oracle/oracle-db-tools#13]
Hi

we are using a common 'header' for almost all our SQL scripts, such as:

DEFINE myjob = '<name>';
WHENEVER SQLERROR EXIT 1
WHENEVER OSERROR EXIT 2
col myuser noprint new_value myuser
col mydate noprint new_value mydate
col mydb noprint new_value mydb
SELECT UPPER(USER) myuser FROM dual;
SELECT TO_CHAR(sysdate,'YYYYMMDDYHH24MISS') mydate FROM dual;
SELECT sys_context('USERENV','DB_NAME') mydb FROM dual;
SET FEEDBACK ON TIME ON TIMING ON ECHO ON HEADING ON VERIFY ON
spool Log/&myjob._&mydb._&myuser._&mydate..log

What would be a good approach to automatically run it, whenever we execute an SQL script? Is there something like login.sql only that is applied to SQL scripts?  Or can I create a javascript that first run this script, and then the one I actually want to execute?

thanks a lot for your help
/Juergen

**Comment by rdruane** [comment]
If you include this in your glogin.sql in the Oracle_Home/sqlplus/admin it will execute for every sqlplus session if your running on the server. This will be executed for all sqlplus sessions. If you only want it for a particular user then put the code in the login.sql in the directory that the sqlplus session is started.

**Comment by jdonnerstag** [comment]
It's not exactly what I was looking for. Since I need a bash script anyways, I put the sql script commands at the beginning of the here document before call the sql script file.
Thanks a lot for your help.
