### ISSUE TITLE
get script file name in JS

### ISSUE THREAD

**Issue by jdonnerstag** [oracle/oracle-db-tools#14]
Hi, 

in my js script I validate the args passed. In case of missing args I'd like to print a "usage: ..." message and then exit. Both I couldn't figure out:
1) what is the name of script file I'm executing? In case it is inline, the name of file it is inlined in. If that is interactive it may be empty or something
2) How can I exit sqlcl from within a js script?

thanks a lot
Juergen

**Comment by krisrice** [comment]
1. If in a .js file; there's an args array and args[0] is the script
2. To exit. The 1 in the parameter is the RC to the calling shell. 0=normal anything is not.
SQL> script
  2* java.lang.System.exit(1);
  3  /
