### ISSUE TITLE
apex export failing with PLS-00306

### ISSUE THREAD

**Issue by bsurnida** [oracle/oracle-db-tools#15]
Hi,

Is there a specific version of apex/database that the "apex export" within sqlcl or the apxexp.js in this repo works with? Or are there variants per version?

I've tried with the following configuration and the export fails with the error below.
sqlcl - Oracle SQLDeveloper Command-Line (SQLcl) version: 17.4.0.354.2224
apex - Application Express 4.2.6.00.03
db - Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
PL/SQL Release 11.2.0.2.0 - Production
CORE    11.2.0.2.0      Production
TNS for Linux: Version 11.2.0.2.0 - Production
NLSRTL Version 11.2.0.2.0 - Production

SYSTEM@localhost:1521/xe > apex export 146
Exporting application 146APEX: Unable to process request. Verify specified options:
ORA-06550: line 2, column 12:
PLS-00306: wrong number or types of arguments in call to 'EXPORT_APPLICATION_TO_CLOB'
ORA-06550: line 2, column 5:
PL/SQL: Statement ignored

Any there any pointers to have this working with the component versions listed above. We are using Oracle 11gR2 EE in production.

**Comment by bsurnida** [comment]
Same issue with Apex 3.2.1, 11gR2 DB, and SQLcl 17.4

SYSTEM@testvm:1521/testdb > select * from v$version
  2  ;
BANNER
Oracle Database 11g Release 11.2.0.1.0 - 64bit Production
PL/SQL Release 11.2.0.1.0 - Production
CORE    11.2.0.1.0      Production
TNS for Linux: Version 11.2.0.1.0 - Production
NLSRTL Version 11.2.0.1.0 - Production


SYSTEM@testvm:1521/testdb > select * from apex_release
  2  ;
VERSION_NO    API_COMPATIBILITY   PATCH_APPLIED
3.2.1.00.10   2009.01.12

SYSTEM@testvm:1521/testdb > version
Oracle SQLDeveloper Command-Line (SQLcl) version: 17.4.0.354.2224

SYSTEM@testvm:1521/testdb > apex export 146
Exporting application 146APEX: Unable to process request. Verify specified options:
ORA-06550: line 2, column 12:
PLS-00306: wrong number or types of arguments in call to 'EXPORT_APPLICATION_TO_CLOB'
ORA-06550: line 2, column 5:
PL/SQL: Statement ignored

**Comment by bamcgill** [comment]
`HR@slci375.us.oracle.com:2193/DB193P🍻🍺 >connect system/oracle
Connected.
login.sql found in the CWD. DB access is restricted for login.sql.
Adjust the SQLPATH to include the path to enable full functionality.
SYSTEM@db193p🍻🍺 >select * from v$version;

                                                                   BANNER                                                                                  BANNER_FULL                                                             BANNER_LEGACY    CON_ID 
_________________________________________________________________________ ____________________________________________________________________________________________ _________________________________________________________________________ _________ 
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production    Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0    Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production            0 

SYSTEM@db193p🍻🍺 >select * from apex_release;

   VERSION_NO    API_COMPATIBILITY    PATCH_APPLIED 
_____________ ____________________ ________________ 
21.2.0        2021.10.15           APPLIED          

SYSTEM@db193p🍻🍺 >apex help
	Available options:
	list:        Lists applications installed in the database.
	log:         Reports APEX application usage from APEX_WORKSPACE_LOG_SUMMARY.
	export:      Export APEX applications and or workspaces.
SYSTEM@db193p🍻🍺 >apex list
   WORKSPACE_ID                     WORKSPACE    APPLICATION_ID                                            APPLICATION_NAME       BUILD_STATUS  LAST_UPDATED_ON 
_______________ _____________________________ _________________ ___________________________________________________________ __________________ ________________ 
12              COM.ORACLE.CUST.REPOSITORY    8842              Universal Theme Development                                 Run and Develop    22-OCT-21        
10              INTERNAL                      4500              Oracle APEX SQL Workshop                                    Run and Develop    25-JAN-22        
.....
10              INTERNAL                      4600              Oracle APEX Issues                                          Run and Develop    25-JAN-22        
10              INTERNAL                      4650              Oracle APEX Feedback                                        Run and Develop    25-JAN-22        
10              INTERNAL                      4700              Oracle APEX New Service Signup                              Run and Develop    18-OCT-21        
10              INTERNAL                      4750              Oracle APEX Productivity and Sample Applications            Run and Develop    25-JAN-22        

SYSTEM@db193p🍻🍺 >apex export 4650
Exporting Application 4650

SYSTEM@db193p🍻🍺 >!ls f4650.sql 
f4650.sql
SYSTEM@db193p🍻🍺 >
`

**Comment by bamcgill** [comment]
Fixed in 21.4.0 and on OTN
