### ISSUE TITLE
SQLcl alias: escape colon (not a bind variable)

### ISSUE THREAD

**Issue by martindsouza** [oracle/oracle-db-tools#17]
I'd like to create the following `alias` in SQLcl: `alias congiffy=connect giffy/giffy@localhost:32122/orclpdb514.localdomain` This is a shortcut for a connection that I use. The problem when running it is that `:32122` is considered a bind variable and calling it gives me `Error: Alias with binds: not enough binds supplied at run time.`

It would be nice to have some way of escaping colons so they're not bind variables. If this could be done in the xml file for aliases I'm ok with that too.

_Note: I realize the security implications of storing connection strings with passwords as an `alias`. In this case, it's for an local docker DB _

cc: @krisrice

**Comment by bamcgill** [comment]
logged enhancement for this to get voted on

**Comment by bamcgill** [comment]
SQL> alias cb=connect barry/oracle@"slci375.us.oracle.com:2193/DB193P";
SQL> cb
Connected.
SQL> select user from dual;
  USER 
________ 
BARRY
