### ISSUE TITLE
Run OS executable from SQL

### ISSUE THREAD

**Issue by Liturgist** [oracle/oracle-db-tools#20]
I am (still) looking for a way to run a local executable from SQL. Will anything here help with that or could it be added?

**Comment by gvenzl** [comment]
Is that what you are looking for:

> HO[ST] [command]
> Executes an operating system command without leaving SQLcl. Enter HOST without
command to display an operating system prompt. You can then enter multiple
operating system commands.

Check the [Oracle SQL Developer Command Line Quick Reference](https://docs.oracle.com/database/sql-developer-4.2/SQCQR/SQCQR.pdf) for more information.

**Comment by gvenzl** [comment]
Closing due to lack of response.
