### ISSUE TITLE
DBMS output in Java example

### ISSUE THREAD

**Issue by vic-ita** [oracle/oracle-db-tools#21]
I'm thrilled by the potentials shown by the java examples. However, no matter what tweaks I try to pull on ScriptRunnerContext, ScriptRunner or ScriptExecutor I do not seem to be able to enable dbms_output awareness of runner/executor classes.

In a nutshell:
```
BEGIN
DBMS_OUTPUT.PUT_LINE('Hello world');
END;
```
correctly returns the localized version of "PL/SQL procedure successfully completed" but nothing else. I would like to be able to also capture the string "hello world" in my own code.

I looked at decompiled bytecode and ScriptRunnerContext.m_dbmsOutput does not seem to be initialized anywhere in that class. However I'm not at all certain that this is the right place to look at.

**Comment by vitaly-zverev** [comment]
Hello Vic-ita. 
The DBMS_OUTPUT method put 'Hello From PL/SQL' string into buffer on DB side.  If you wish to see buffer's content in reply, then just add "set serveroutput on", looks like:
 
set serveroutput on
BEGIN
  DBMS_OUTPUT.PUT_LINE('Hello From PL/SQL');
END;
/

and got reply:

{
    "env": {
        "defaultTimeZone": "GMT"
    },
    "items": [
        {
            "statementId": 1,
            "statementType": "sqlplus",
            "statementPos": {
                "startLine": 1,
                "endLine": 1
            },
            "statementText": "set serveroutput on",
            "response": [],
            "result": 0
        },
        {
            "statementId": 2,
            "statementType": "plsql",
            "statementPos": {
                "startLine": 2,
                "endLine": 5
            },
            "statementText": "BEGIN\n  DBMS_OUTPUT.PUT_LINE('Hello From PL/SQL');\nEND;",
            "response": [
                "Hello From PL/SQL\n\n",
                "\nPL/SQL procedure successfully completed.\n\n"
            ],
            "dbmsOutput": "Hello From PL/SQL\n\n",
            "result": 0
        }
    ]
}

**Comment by krisrice** [comment]
FYI decompiling violates EULA.

@vic-ita is correct, just turn on `set serveroutput on`

**Comment by vitaly-zverev** [comment]
@krisrice FYI I'm not vic-ita, who decompiling something :)

**Comment by krisrice** [comment]
whoops got names backwards.  
@vitaly-zverev is correct on enabling.
@vic-ita don't decompile.
