### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by moose56** [oracle/oracle-db-tools#22]
Hi,

In this bit of the parse script example:

```java
while ( (  cmd = parser.next() ) != null ) {
    // do something fancy based on a cmd
    sr.run(cmd);
    // check success/failure of the command
    String errMsg = (String) ctx.getProperty(ctx.ERR_MESSAGE);
    if ( errMsg != null   ){
    // react to a failure
        System.out.println("**FAILURE**" + errMsg);
    }				
}
```
Under what circumstances does the `ctx.getProperty(ctx.ERR_MESSAGE);` get set. I have tried a couple of scripts that should result in an error but it is always null.

David.

**Comment by vic-ita** [comment]
That happened to me too. I got it working with

`ctx.getProperty(ScriptRunnerContext.ERR_SQLCODE);`

and/or

`(String) ctx.getProperty(ScriptRunnerContext.ERR_MESSAGE_SQLCODE);`
