### ISSUE TITLE
Oracle profiler

### ISSUE THREAD

**Issue by hinalborad** [oracle/oracle-db-tools#28]
Is there profiler in Oracle like SQL profiler in the SQL server?

**Comment by rajivgupta780184** [comment]
Yes, Oracke has dbms_ profiler pkg

**Comment by hinalborad** [comment]
dbms_profiler provides monitoring and performance of queries but we need a tool like SQL Profiler that can be used to trace tables, queries, views and functions that are being used once we click on a button from the front end or perform any event form front end (Web application).

**Comment by ahdung** [comment]
i just from mssql come to oracle, i feel the oracle's tools are really weak.
