### ISSUE TITLE
sqlcl throws NullPointerException on startup

### ISSUE THREAD

**Issue by sify21** [oracle/oracle-db-tools#29]
sqlcl version:
19.2.1.246.1707
![0880c08b0110978a8709](https://user-images.githubusercontent.com/11829223/70212736-d413cf00-1772-11ea-8116-7c0d79562a0e.png)

**Comment by dwierenga** [comment]
No idea if this is your issue, but I was getting a similar error when I had `set editing-mode vi` in my `~/.inputrc` file

**Comment by bamcgill** [comment]
This will be supported in our next release which will ship jline3 support and vi/emacs bindings out of the box.
