### ISSUE TITLE
Support for vi keybindings

### ISSUE THREAD

**Issue by dwierenga** [oracle/oracle-db-tools#31]
Is there a plan for supporting vi keybindings?   I have a lot of muscle-memory for vi keybindings, and I'm eager to leverage them with sqlcl.  I know sqlplus doesn't support vi keybindings either, but using rlwrap they mostly work.  However, sqlcl doesn't seem to support vi keybindings, nor does rlwrap help it.

**Comment by thatjeffsmith** [comment]
Yes, in fact I saw the demo today, vi or emacs.

Later this year, stay tuned.

**Comment by bamcgill** [comment]
Next release of SQLcl will have this and vi bindings by default with an upgrade to using JLine3 as a dependency.
