### ISSUE TITLE
Some Standard SQLcl script commands don't work from Java with Connection Pools

### ISSUE THREAD

**Issue by Bob-Bogardus** [oracle/oracle-db-tools#36]
It appears that several standard SQLcl script commands don't work from Java. For example:
- ORA-00922: missing or invalid option
    set null '^'
    set verify off
- ORA-00900: invalid SQL statement
    define myparam = '&1'

These work fine when running SQLcl on the command line.

I'm using SQLcl 21.1.1 and this site's pattern from "sqlcl/java/README.md"
  ScriptExecutor sqlcl = new ScriptExecutor(conn);
  sqlcl.setStmt("@/mySqlclScript.sql");
  sqlcl.run();

We have an extensive library of interconnected SQLPlus scripts that we've automated by calling sqlplus.exe from Java.
We'd like to replace that with java based SQLcl, ideally without a major rewrite of our scripts.

Questions:
- Should all the SQLcl capabilities be available when calling from Java?
  2.1 Alphabetic List of SQLcl Commands
  https://docs.oracle.com/en/database/oracle/sql-developer-command-line/21.1/sqcug/working-sqlcl.html#GUID-DB0D123B-AFA1-4C5A-AB2A-A7B59863C9B9
  - If so, how can I get null, verify, define, etc to work?

- If not, is there documentation on which commands do NOT work from Java?
  Are there work-arounds?
  e.g. DEFINE is necessary when making calls to other @@childScripts.sql... how can that be done from Java?

- Is there JavaDoc for SQLcl?
  For example, this command doesn't appear to set the base directory - setStmt() appears to require absolute path
  sqlcl.setDirectory(sqlDirPath);

- Let me know if there's a different forum I should use for these questions.

Thanks!
Bob

**Comment by Bob-Bogardus** [comment]
Example:
- V:\scripts\testParam.sql

SET SQLFORMAT DEFAULT
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYYMMDD';
set null '^'
set verify off

define myvar = '&1'

define yourvar = '&2'

- sqlcl.setStmt("V:\scripts\testParam.sql AbCdEfG 012345");
  sqlcl.run();

SQL Format Cleared

Session altered.


Error starting at line : 3 File @ V:\scripts\testParam.sql
In command -
set null '^'
Error report -
ORA-00922: missing or invalid option


Error starting at line : 4 File @ V:\scripts\testParam.sql
In command -
set verify off
Error report -
ORA-00922: missing or invalid option

old:define myvar = '&1'

new:define myvar = 'AbCdEfG'

Error starting at line : 6 File @ V:\scripts\testParam.sql
In command -
define myvar = '&1'
Error report -
ORA-00900: invalid SQL statement

old:define yourvar = '&2'

new:define yourvar = '012345'

Error starting at line : 8 File @ V:\scripts\testParam.sql
In command -
define yourvar = '&2'
Error report -
ORA-00900: invalid SQL statement

**Comment by Bob-Bogardus** [comment]
Thanks for assigning this to Brian last Friday. This is my first post here, how long does it typically take for a response? Is there a better forum to use? e.g. should I post this in my OTN support account?

**Comment by Mmm-Biscuits** [comment]
its being looked into but if this is a support issue, please log an SR.

**Comment by krisrice** [comment]
@Bob-Bogardus do you have a full example of what's not working? Something I can run and see what's going on ?

**Comment by Bob-Bogardus** [comment]
Thanks Brian!

Thanks Kris: Yes, I have an example above - the 2nd comment from me. (V:\scripts\testParam.sql)

Basically, just put these in your SQL file - they all fail for me when called from the java api...
set null '^'
set verify off
define myvar = 'MyMessage'

**Comment by krisrice** [comment]
I mean the full example. Something I can just run like you are trying to do. So Java and all that you are calling that with.

**Comment by Bob-Bogardus** [comment]
Sure, I'll extract my code into a test application and upload. I'll have it later today. Thanks.

**Comment by Bob-Bogardus** [comment]
Hi Kris,
Thanks for your suggestion. It's been a very fruitful exercise:
these commands work FINE using java.sql.DriverManager (from the provided example).

We're using a Spring applicationContext file, with a com.zaxxer.hikari.HikariDataSource connection pool, and the commands fail with that.

Never occurred to me that the connection could cause a problem.

So, I am expanding my test class to try to clarify what works and what doesn't (e.g. is it Spring itself, or Hikari, etc).

I'll report back when I get more info.

Thanks again.
Bob

**Comment by krisrice** [comment]
Excellent you are making headway. Hit me up when/if you hit the next issue.

**Comment by Bob-Bogardus** [comment]
Hi Kris,
OK, looks like it fails with Spring connection pools - I tried both Commons DBCP and Hikari.
It does work with Spring using org.springframework.jdbc.datasource.DriverManagerDataSource

I've attached my code designed to run on Windows (will run on linux with the appropriate adjustments).
See the README.txt for setup and info.
It executes 4 types of connections. Put your DB parameters in app.properties for the regular DriverManager execution, and in the applicationContext.xml to exercise the 3 types of Spring connections.

Our hope was not only to use SQLcl API to eliminate java calls to the "sqlplus" binary on the OS, but also to take advantage of connection pools.

I'm not familiar with the inner workings of connection pools - do you know some reason offhand why they wouldn't work with some of the SQLcl commands? Any thoughts on a workaround?

Let me know if you see something in my code that needs correction.

Much appreciated!
Bob

[issue36sqlcl.zip](https://github.com/oracle/oracle-db-tools/files/6664176/issue36sqlcl.zip)

**Comment by krisrice** [comment]
Kinda what I was thinking it'd be. The pools are wrapping the real connection. 

If you add this `ScriptExecutor sqlcl = new ScriptExecutor((OracleConnection)conn);` you'll see the cast issues. SQLcl code base works on any database however for oracle lingo we need an oracle connection. That explains why some command did not work for this case.   

Here's the change to put into your code and it all works..


```
		ScriptExecutor sqlcl =null;
		if ( conn.isWrapperFor(OracleConnection.class) ) {
			sqlcl = new ScriptExecutor(conn.unwrap(OracleConnection.class));
		} else {
			 sqlcl = new ScriptExecutor(conn);
		}
```

**Comment by Bob-Bogardus** [comment]
That fixed it! AWESOME!

Thanks so much Kris!
Bob

**Comment by krisrice** [comment]
Let me know when you get it all sorted. It'd be great to hear how it's helping.
