### ISSUE TITLE
SQLcl bug in sqlcl script.

### ISSUE THREAD

**Issue by depaulmillz** [oracle/oracle-db-tools#43]
Hi. I didn't know where else to report this.

Your sql script in sqlcl version 21.4.1.17.1458 has a bug on line 610 that prevents me from using it. It's a simple fix. The code has `$JAVA` to run the java version, but the path to my java version has a space in it. This causes it to interpret the `$JAVA` variable as multiple arguments. Instead quotes should be added to make the line say `"$JAVA"`. I did this fix myself and it fixed the issue.

**Comment by krisrice** [comment]
doh :(  we're on it.

**Comment by bamcgill** [comment]
Bugged and fixed in dev.  Will be in next release (22.1)
