### ISSUE TITLE
apxexp logic error for -skipExportDate option

### ISSUE THREAD

**Issue by mark-lancaster** [oracle/oracle-db-tools#5]
Using apxexp with -skipExportDate option results in a file with all blank lines except the export date.

Line 270 is:
                    if ( ! ( this.options.skipDate &&  line.indexOf("--   Date and Time:") != 0  ) ) {
should be:
                    if ( ! ( this.options.skipDate &&  line.indexOf("--   Date and Time:") == 0  ) ) {

**Comment by krisrice** [comment]
Change is in.
