### ISSUE TITLE
apximp.js does abort with translation

### ISSUE THREAD

**Issue by hairpin666** [oracle/oracle-db-tools#6]
Hi, 

I tried to import our apex application with the apximp.js script. It works fine if I do not export the translation.
When I embed the translation with the application export the import script stops at the following line (see picture below). I already tried to change the affected SQL region but no success. What's the issue here? Any ideas?

Thanks

![unbenannt](https://cloud.githubusercontent.com/assets/16673188/23367322/230c1396-fd0a-11e6-9780-026cbfc370ab.PNG)

**Comment by hairpin666** [comment]
I'm using the -offset for the import, does not help. I guess it is not a sqlcl script problem but I still can not figure out what the problem is.

**Comment by gvenzl** [comment]
Hey @hairpin666, do you still face this issue?

**Comment by gvenzl** [comment]
Closing due to lack of response.
