### ISSUE TITLE
cannot get a blob variable as Blob with ctx.getVarMap() 

### ISSUE THREAD

**Issue by stoopenf** [oracle/oracle-db-tools#8]
In sqlcl I entered the following commands:

```
var test blob
begin select file_content into :test from MIG_PROJECT_PROJECT_FILES where rownum = 1; end;
/
```

This load database blob into the bind variable :test

I have created javascript file blob2file.js with the following code:

```
var blobvar = ctx.getVarMap().get(args[1].toUpperCase()).getValue();
var blobStream = blobvar.getBinaryStream(1);
var path = java.nio.file.FileSystems.getDefault().getPath(args[2]);
java.nio.file.Files.copy(blobStream ,path);
```

I run the javascript with the following command:

```
script test testoutput
```

This result in the error `"javax.script.ScriptException: TypeError: blobvar.getBinaryStream is not a function in <eval> at line number 2"`

So I think the getValue() dit not provide a Blob variable.

How should I fetch a bind variable from the Blob type.

**Comment by gvenzl** [comment]
@krisrice, can you take a look at this please.

**Comment by totierne** [comment]
Blob value was previously stored as hex string - 
if isLastSetObj() is set the related Blob object can be retrieved by getValueObj.
(There are edge cases (old code/binds teated differently) where (isLastSetObj()==false)).
(This is only used for blobs at the moment - it allows free blob on subsequent anonymous block).

Tested in SQLcl17.4: (with hextoraw('FF')) single character var test blob .
cat /home/oracle/blob2file.js
var blobvar = null;
if (ctx.getVarMap().get(args[1].toUpperCase()).isLastSetObj()) {
blobvar = ctx.getVarMap().get(args[1].toUpperCase()).getValueObj();
var blobStream = blobvar.getBinaryStream(1);
var path = java.nio.file.FileSystems.getDefault().getPath(args[2]);
java.nio.file.Files.copy(blobStream ,path);
}

**Comment by stoopenf** [comment]
Thank yo so much. Wat a nice start of 2018.
In the version I used (17.2.0) it was not working, but in version 17.4.0 it works perfectly.

Thank you for finding the solution of my problem.
